### PR TITLE
UI changes, network settings added

### PR DESCRIPTION
**Pull request by jsteltze**
- apply System look&feel on start-up
- menu icons added (dont worry, I checked license, they are license free)
- changed layout of SettingsDialog
- added network settings for using proxy
- added network settings for checking updates
- added quick search text field in CacheListView
- added unit test UtilTest

### CODE REVIEW

**Comment by FriedrichFroebel** [comment]
Thanks for your contribution. Unfortunately I cannot merge this PR for now as there are file conflicts. Additionally this includes quite a lot of different changes/features in one PR, which should rather be separate PRs to keep each change maintainable.

Some additional notes about specific functionality (this list is just from a quick look at it, not from a deeper analysis):

* The proxy settings should probably be retrieved in the network class or in a dedicated method, not directly inside the `main` method.
* The quick search functionality seems like a reasonable idea, but do we really need all the listeners on the frame instead of the text field?
* The icons seem useful, although they seem to be missing source links (except the notice). Additionally we should probably use a common helper function to load them to avoid code duplicates.
* Why is the update check setting using a string? Cannot we use a boolean value for it?
* What is the reason for removing the bounds of the settings dialog?
* I am not sure whether the `UtilTest` makes sense - with the latest release there already is a way to display duplicate search results from within the GUI - by starting the application with the `CMANAGER_LOG_LEVEL` environment value being set to `ALL`.

**Comment by jsteltze** [comment]
Hi

 

Please let me know, what I can edit to include my changes.

 

Please also let me know, if / where you dont want me to change things. Does not make sense for me to put effort into changes which will not be merged ;-)

 

Johannes

 


Gesendet: Donnerstag, 11. Juni 2020 um 10:36 Uhr
Von: "FriedrichFroebel" <notifications@github.com>
An: "FriedrichFroebel/cmanager" <cmanager@noreply.github.com>
Cc: "jsteltze" <johannes.steltzer@gmx.net>, "Author" <author@noreply.github.com>
Betreff: Re: [FriedrichFroebel/cmanager] UI changes, network settings added (#32)


 

Thanks for your contribution. Unfortunately I cannot merge this PR for now as there are file conflicts. Additionally this includes quite a lot of different changes/features in one PR, which should rather be separate PRs to keep each change maintainable.

Some additional notes about specific functionality (this list is just from a quick look at it, not from a deeper analysis):


	The proxy settings should probably be retrieved in the network class or in a dedicated method, not directly inside the main method.

	
		I was thinking it is a good idea to set them as early as possible, so early network functions (such as searching for updates) dont run into missing proxy settings.
	
	
	The quick search functionality seems like a reasonable idea, but do we really need all the listeners on the frame instead of the text field?
	
		okay, possible to add the listeners as inner classes
	
	
	The icons seem useful, although they seem to be missing source links (except the notice). Additionally we should probably use a common helper function to load them to avoid code duplicates.
	
		The icons which I used dont require source links. Agree, a Icon-helper class would be useful.
	
	
	Why is the update check setting using a string? Cannot we use a boolean value for it?
	
		As far as I see the Settings class only supports String:key -> String:value. I did not want to change too much logic here in terms of new data types.
	
	
	What is the reason for removing the bounds of the settings dialog?
	
		To be honest the layout of the SettingsDialog did not look great (at least on Win10). I would always prefer to use layout-managers / panels instead of hard-coded pixel values.
	
	
	I am not sure whether the UtilTest makes sense - with the latest release there already is a way to display duplicate search results from within the GUI - by starting the application with the CMANAGER_LOG_LEVEL environment value being set to ALL.
	
		okay. Did not know this new release function. I wanted to check some specific Caches and I was just looking for a easy entry point, if I dont have gpx files for it...

**Comment by FriedrichFroebel** [comment]
I will merge changes if each PR just includes one specific feature (like one PR for adding the quick search functionality, one PR for adding icons, one PR for improving the settings dialog) - otherwise reviewing/discussing your changes is too hard to handle.

So to get your edits merged, rebase your fork on the latest master branch first to prevent further merge conflicts. Then you can create feature-specific branches on your fork (based upon the master branch) and send each of the branches/features as a separate PR. If you have any problems with this, I will be glad to support you (if you prefer to do this in German, this is no problem for me) - each contribution which improves the application is valuable.

**Comment by FriedrichFroebel** [comment]
Closing due to the lack of response. Feel free to open new PRs if you have adressed the aforementioned issues.

**Pull request closed without merging**
